services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dating
      POSTGRES_PASSWORD: dating
      POSTGRES_DB: dating
    ports:
      - '5432:5432'
    volumes:
      - dating-pg:/var/lib/postgresql/data

volumes:
  dating-pg:
