import { Platform, StyleSheet } from 'react-native';
import { color, font } from '../theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: color.bg },
  scroll: { flexGrow: 1, paddingBottom: 28 },
  hero: { paddingTop: 28, paddingBottom: 8 },
  heroInner: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
    paddingHorizontal: 24,
  },
  mark: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: color.roseSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  markText: { color: color.rose, fontSize: 20, fontWeight: '700' },
  kicker: {
    color: color.rose,
    fontFamily: font.body,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.4,
    marginBottom: 6,
  },
  title: {
    color: color.ink,
    fontFamily: font.display,
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '700',
    marginBottom: 8,
  },
  subtitle: {
    color: color.mute,
    fontFamily: font.body,
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 320,
  },
  sheet: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 16,
  },
  card: {
    backgroundColor: color.paper,
    borderRadius: 24,
    padding: 20,
    gap: 16,
  },
  section: {
    fontFamily: font.body,
    fontSize: 13,
    fontWeight: '600',
    color: color.mute,
    marginTop: 4,
  },
  field: { gap: 8 },
  fieldLabel: { fontFamily: font.body, fontSize: 13, fontWeight: '600', color: color.ink },
  input: {
    fontFamily: font.body,
    fontSize: 16,
    color: color.ink,
    backgroundColor: color.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: color.line,
    paddingHorizontal: 16,
    paddingVertical: 14,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none' as const } : {}),
  },
  inputOn: { borderColor: color.rose, backgroundColor: color.paper },
  multiline: { minHeight: 96, textAlignVertical: 'top' },
  chipBlock: { gap: 8 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chipsNowrap: { flexWrap: 'nowrap' },
  chip: { borderRadius: 999, paddingHorizontal: 16, paddingVertical: 9, borderWidth: 1 },
  chipOn: { backgroundColor: color.rose, borderColor: color.rose },
  chipOff: { backgroundColor: color.surface, borderColor: color.line },
  chipText: { fontFamily: font.body, fontSize: 14, fontWeight: '600' },
  chipTextOn: { color: color.onRose },
  chipTextOff: { color: color.ink },
  check: {
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: color.line,
    backgroundColor: color.surface,
    alignItems: 'flex-start',
  },
  checkOn: { borderColor: color.rose, backgroundColor: color.roseSoft },
  box: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: color.mute,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  boxOn: { backgroundColor: color.rose, borderColor: color.rose },
  tick: { color: color.onRose, fontSize: 12, fontWeight: '700' },
  checkCopy: { flex: 1, gap: 4 },
  checkLabel: { fontFamily: font.body, fontSize: 15, color: color.ink, lineHeight: 21 },
  checkHint: { fontFamily: font.body, fontSize: 13, color: color.mute, lineHeight: 18 },
  cta: {
    backgroundColor: color.rose,
    borderRadius: 999,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 4,
  },
  ctaPressed: { backgroundColor: color.rosePressed },
  ctaText: {
    color: color.onRose,
    fontFamily: font.body,
    fontSize: 16,
    fontWeight: '700',
  },
  ghost: { alignItems: 'center', paddingVertical: 10 },
  ghostText: { color: color.rose, fontFamily: font.body, fontSize: 15, fontWeight: '600' },
  muteNote: {
    fontFamily: font.body,
    fontSize: 13,
    color: color.mute,
    textAlign: 'center',
    lineHeight: 18,
  },
  error: { color: color.danger, fontFamily: font.body, fontSize: 14, lineHeight: 20 },
  portrait: {
    width: '100%',
    aspectRatio: 0.72,
    borderRadius: 28,
    backgroundColor: color.surface,
  },
  portraitFallback: {
    width: '100%',
    aspectRatio: 0.72,
    borderRadius: 28,
    backgroundColor: color.roseSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  portraitInitial: { color: color.rose, fontFamily: font.display, fontSize: 64, fontWeight: '700' },
  photoCard: {
    flex: 1,
    minHeight: 0,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: color.surface,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  photoFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: color.surface,
  },
  photoFallback: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: color.roseSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoCaption: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingBottom: 84,
    paddingTop: 56,
    backgroundColor: color.overlay,
  },
  photoName: { color: color.onRose, fontFamily: font.display, fontSize: 32, fontWeight: '700' },
  photoBadge: {
    position: 'absolute',
    top: 22,
    left: 12,
    zIndex: 3,
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  photoBadgeText: { color: color.onRose, fontFamily: font.body, fontSize: 12, fontWeight: '600' },
  photoBio: { color: color.onRose, fontFamily: font.body, fontSize: 14, marginTop: 6, opacity: 0.88 },
  photoDots: { position: 'absolute', top: 10, left: 12, right: 12, flexDirection: 'row', gap: 4, zIndex: 2 },
  photoDot: { flex: 1, height: 3, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.4)' },
  photoDotOn: { backgroundColor: '#FFFFFF' },
  fixed: { flex: 1, minHeight: 0, overflow: 'hidden' },
  actions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
    gap: 22,
  },
  circle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color.paper,
    shadowColor: '#1A1A1A',
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  circleLg: { width: 78, height: 78, borderRadius: 39 },
  circlePass: { backgroundColor: color.paper },
  circleLike: {
    backgroundColor: color.rose,
    shadowColor: color.rose,
    shadowOpacity: 0.38,
  },
  circlePassText: { color: color.rose, fontSize: 26, fontWeight: '700' },
  circleLikeText: { color: color.onRose, fontSize: 30, fontWeight: '700' },
  matchMask: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(18, 10, 16, 0.88)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    gap: 12,
  },
  matchTitle: {
    color: color.onRose,
    fontFamily: font.display,
    fontSize: 36,
    fontWeight: '700',
    textAlign: 'center',
  },
  matchHint: { fontFamily: font.body, fontSize: 13, color: color.mute, marginTop: 2 },
  bubbleMe: {
    alignSelf: 'flex-end',
    backgroundColor: color.rose,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    maxWidth: '80%',
  },
  bubbleThem: {
    alignSelf: 'flex-start',
    backgroundColor: color.surface,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    maxWidth: '80%',
  },
  bubbleMeText: { color: color.onRose, fontFamily: font.body, fontSize: 15, lineHeight: 21 },
  bubbleThemText: { color: color.ink, fontFamily: font.body, fontSize: 15, lineHeight: 21 },
});
